model:
  detector:
    type: "yolo11n"
    confidence_threshold: 0.5
    weights_path: "src/data/weights/yolo11n.pt"
    finetuned_weights_path: "/Users/kobe/Documents/UCLL/School 2024-2025/AI Applications/ai-app-bot-brigade/src/data/weights/best_4.pt"

  classifier:
    input_size: 128
    out_channels: 64
    num_layers: 4
    kernel_size: 3
    dropout: 0.5
    model_path: "C:/Users/mathi/OneDrive/Desktop/projects/bot-brigade/src/data/weights/best_model.pth"

  keypoint_extractor:
    complexity: 1
    min_confidence: 0.5

training_detector:
  epochs: 10
  learning_rate: 0.001
  weight_decay: 0.0001

training_classifier:
  epochs: 20
  learning_rate: 0.001
  weight_decay: 0.0001
  batch_size: 32

fall_detection_data:
  img_size: 640

classifier_data:
  train_path: "/Users/kobe/Documents/UCLL/School 2024-2025/AI Applications/ai-app-bot-brigade/src/data/classifier_data/train"
  valid_path: "/Users/kobe/Documents/UCLL/School 2024-2025/AI Applications/ai-app-bot-brigade/src/data/classifier_data/valid"
  test_path: "/Users/kobe/Documents/UCLL/School 2024-2025/AI Applications/ai-app-bot-brigade/src/data/classifier_data/test"
  img_size: 640

system:
  device: "cuda"
  num_workers: 4

evaluation:
  ground_truth_path: "/Users/kobe/Documents/UCLL/School 2024-2025/AI Applications/ai-app-bot-brigade/src/data/pipeline_eval_data/ground_truth.json"
  results_path: "/Users/kobe/Documents/UCLL/School 2024-2025/AI Applications/ai-app-bot-brigade/src/models/metrics/evaluation_results.csv"
